title: hporro
name: hporro
markdown: kramdown
kramdown:
    math_engine: mathjax
permalink: /:collection/:title/
collections:
    projects:
        output: true
    blog:
        output: true
    images:
collections_dir: postFiles
